# -*- coding: utf-8 -*-
"""KT-AI:index,tuple,dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nJvKUDKiV_pKHqdk4wN8_fAbK2CnTGnU

# 인덱스(Index)
"""

x = "Rome is not built in a day!"

print(x[0])
print(x[-1])
print(x[-6])

"""Slicing

"""

x = "Rome is not built in a day!"

print(x[12:])
print(x[12:17])
print(x[:7])
print(x[:])
print(x[12:-7]) #마이너스

"""# list

"""

a = [1,2,3,4,5,6]
print(a)

b = list(range(1,10,2))

print(b)

a = [1,2,3,4,5,5,6,7,7,8,89,9]
b = list(range(1,10,2))

a.append(4)
print(a)
a.insert(1,5)
print(a)
a.extend(b)
print(a)
a.remove(3)
print(a)
a.count(1)
a.sort()
print(a)
a.sort(reverse = True)
print(a)

"""# Tuple"""

a=(1,2,3)
b = 1,2,3

print(a)
print(b)

"""# 딕셔너리"""

members = {"name":"안지영","age":30,"emil":"leeppap1235@gmail.com"}
print(members.keys())
print(members.values())
print(members.items())
print(members.get("name"))

print("name" in members)
print("babycat" in members) #이 딕셔너리 안에 키 값이 존재 여부를 보는 함수

members.clear()

print(members)