# -*- coding: utf-8 -*-
"""KT-AI:DATA FRAME 변형.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RxNzvyZXYjOH4dSz4s4ERIa5dX-soDLK
"""

import pandas as pd
import numpy as np

ct = pd.read_csv('/content/sample_data/FL_insurance_sample.csv',encoding='cp949')
ct

gc = ct.groupby('construction')

gc.groups

gc.count() #데이터 크기

gc.mean()

gc.max()[["policyID "]]

data  = pd.DataFrame({'id': ['1','1','1','2','2','2','3','3','3'],'cd':['p1','p2','p3','p1','p2','p3','p1','p2','p3'],"grade":['A','A','A','A','A','A','B','B','B'],'amt':[30,10,0,40,15,30,0,0,30]})

data

data.pivot(index = 'id',columns = 'cd',values = 'amt')

data.pivot_table(index = 'id',columns = 'cd',values = 'amt')

data.pivot_table(index = ['id','grade'],columns = 'cd',values = 'amt') # privot와 다르게 두개의 인덱스 값을 추가해서 할 수있음





"""pivot은 중복이 있을 경우 에러를 반환

pivot_table은 aggregation 함수를 활용하여 처리함
"""

data.pivot_table(index = 'grade',columns = 'cd',values = 'amt',aggfunc = np.sum ) # privot와 다르게 두개의 인덱스 값을 추가해서 할 수있음